pybo/views/answer_views.py
from datetime import datetime
from .auth_views import login_required
from flask import Blueprint, url_for, request, render_template, g, flash
from werkzeug.utils import redirect

from .. import db
from ..forms import AnswerForm
from ..models import Community, Answer

bp = Blueprint('answer', __name__, url_prefix='/answer')


@bp.route('/create/<int:community_id>', methods=('POST',))
@login_required
def create(community_id):
    form = AnswerForm()
    community = Community.query.get_or_404(community_id)
    if form.validate_on_submit():
        content = request.form['content']
        answer = Answer(content=content, create_date=datetime.now(), user=g.user)
        community.answer_set.append(answer)
        db.session.commit()
        return redirect(url_for('community.detail', community_id=community_id))
    return render_template('community/community_detail.html', community=community, form=form)


@bp.route('/modify/<int:answer_id>', methods=('GET', 'POST'))
@login_required
def modify(answer_id):
    answer = Answer.query.get_or_404(answer_id)
    form = AnswerForm(obj=answer)
    # 보안
    # if g.user != answer.user:
    #     # flash('수정권한이 없습니다')
    #     print("수정 권한 없음")
    #     print(g.user+" "+answer.user)
    #     return '<script>alert("수정권한이 없습니다");location.href="/answer/detail/' + str(answer.community.id) + '"</script>'
    if request.method == "POST":
        form = AnswerForm()
        if form.validate_on_submit():
            form.populate_obj(answer)
            answer.modify_date = datetime.now()  # 수정일시 저장
            db.session.commit()
            return '<script>alert("수정되었습니다.");location.href="/community/detail/' + str(answer.community.id) + '"</script>'

    return render_template('answer/answer_form.html', form=form)


@bp.route('/delete/<int:answer_id>', methods=('GET', 'POST'))
@login_required
def delete(answer_id):
    answer = Answer.query.get_or_404(answer_id)
    community_id = answer.community.id
    if g.user != answer.user and g.user.email != "biteup@biteup.com":
        print("삭제 권한 없음")
        print(g.user.email+" -> "+answer.user.email)
        return '<script>alert("삭제권한이 없습니다");location.href="/community/detail/'+str(community_id)+'"</script>'
    else:
        db.session.delete(answer)
        db.session.commit()
        print("댓글이 삭제되었음")
        print(g.user.email+" -> "+answer.user.email)
    return '<script>alert("삭제되었습니다.");location.href="/community/detail/'+str(community_id) + '"</script>'

pybo/views/community_views.py
import os
from datetime import datetime, date, timedelta
from pybo.views.auth_views import login_required
from flask import Blueprint, render_template, request, url_for, g, flash, send_file
from werkzeug.utils import secure_filename

from .. import db
from ..forms import CommunityForm, AnswerForm
from ..models import Community, Answer, User

path = os.getcwd()
UPLOAD_FOLDER = os.path.join(path, 'pybo\\static\\upload_file')
bp = Blueprint('community', __name__, url_prefix='/community')

file_path = "templates/upload_file/"


@bp.route('/list')
@login_required
def _list():
    # 입력 파라미터
    page = request.args.get('page', type=int, default=1)
    kw = request.args.get('kw', type=str, default='')

    # 조회
    community_list = Community.query.order_by(Community.create_date.desc())
    if kw:
        search = '%%{}%%'.format(kw)
        sub_query = db.session.query(Answer.community_id, Answer.content, User.username) \
            .join(User, Answer.user_id == User.id).subquery()
        community_list = community_list \
            .join(User) \
            .outerjoin(sub_query, sub_query.c.community_id == Community.id) \
            .filter(Community.subject.ilike(search) |  # 제목
                    Community.content.ilike(search) |  # 내용
                    User.username.ilike(search) |  # 작성자
                    sub_query.c.content.ilike(search) |  # 답변내용
                    sub_query.c.username.ilike(search)  # 답변작성자
                    ) \
            .distinct()

    # 페이징
    community_list = community_list.paginate(page, per_page=10)
    return render_template('community/community_list.html', community_list=community_list, page=page, kw=kw)


@bp.route('/detail/<int:community_id>/')
@login_required
def detail(community_id):
    form = AnswerForm()
    community = Community.query.get_or_404(community_id)

    #조회수 증가
    community.hits = community.hits + 1
    db.session.commit()

    # 입력 파라미터
    page = request.args.get('page', type=int, default=1)
    kw = request.args.get('kw', type=str, default='')

    # 조회
    community_list = Community.query.order_by(Community.create_date.desc())
    if kw:
        search = '%%{}%%'.format(kw)
        sub_query = db.session.query(Answer.community_id, Answer.content, User.username) \
            .join(User, Answer.user_id == User.id).subquery()
        community_list = community_list \
            .join(User) \
            .outerjoin(sub_query, sub_query.c.community_id == Community.id) \
            .filter(Community.subject.ilike(search) |  # 제목
                    Community.content.ilike(search) |  # 내용
                    User.username.ilike(search) |  # 작성자
                    sub_query.c.content.ilike(search) |  # 답변내용
                    sub_query.c.username.ilike(search)  # 답변작성자
                    ) \
            .distinct()
    # 페이징
    community_list = community_list.paginate(page, per_page=10)
    return render_template('community/community_detail.html', community=community, form=form, community_list=community_list, page=page, kw=kw)


@bp.route('/create', methods=('GET', 'POST'))
@login_required
def create():
    form = CommunityForm()
    filename = None

    if request.method == 'POST' and form.validate_on_submit():
        if request.files['file']:
            filename = file_upload(request.files['file'])
            if(filename == "error"):
                return '<script>alert("허용된 확장자가 아닙니다.");location.href="/community/detail"</script>'

        community = Community(subject=form.subject.data, content=form.content.data, create_date=datetime.now(),
                              user=g.user, file=filename, hits=1)

        db.session.add(community)
        db.session.commit()

        #로그
        print("게시글 생성")
        print("작성자 : " + g.user.email)
        print("별명 : " + g.user.username)
        print("제목 : " + form.subject.data)
        print("내용 : "+ form.content.data)
        if filename is not None:
            print("업로드 파일 : "+ filename)
        ###
        return '<script>alert("작성 되었습니다.");location.href="/community/list"</script>'
    return render_template('community/community_form.html', form=form)


@bp.route('/modify/<int:community_id>', methods=('GET', 'POST'))
@login_required
def modify(community_id):
    community = Community.query.get_or_404(community_id)
    # 보안
    # if g.user != community.user:
    #     print("게시글 수정 권한 없음")
    #     print(g.user.email+"->"+community.user.email)
    #     return '<script>alert("수정권한이 없습니다.");location.href="/community/detail/' + str(community_id) + '"</script>'
    if request.method == 'POST':  # POST 요청
        form = CommunityForm()
        if form.validate_on_submit():
            if request.files['file']:
                filename = file_upload(request.files['file'])
                if(filename == "error"):
                    return '<script>alert("허용된 확장자가 아닙니다.");location.href="/community/detail"</script>'
                community.file = filename

            #로그
            print("게시글 수정됨")
            print(g.user.email+" -> "+community.user.email)
            print("제목 : "+community.subject+" -> "+form.subject.data)
            print("본문 : "+community.content+" -> "+form.content.data)
            ###

            community.subject = form.subject.data
            community.content = form.content.data
            community.modify_date = datetime.now()  # 수정일시 저장
            db.session.commit()

            return '<script>alert("수정되었습니다.");location.href="/community/detail/' + str(community_id) + '"</script>'
    else:  # GET 요청
        form = CommunityForm(obj=community)
    return render_template('community/community_form.html', form=form)


@bp.route('/delete/<int:community_id>')
@login_required
def delete(community_id):
    community = Community.query.get_or_404(community_id)
    if g.user != community.user and g.user.email != "biteup@biteup.com":
        print("게시글 삭제 권한 없음")
        print(g.user.email+" -> "+community.user.email)
        return '<script>alert("삭제 권한이 없습니다.");location.href="/community/detail/' + str(community_id) + '"</script>'

    print("게시글 삭제됨")
    print(g.user.email+" -> "+community.user.email)
    print("제목 : " + community.subject)
    print("본문 : " + community.content)
    ####

    db.session.delete(community)
    db.session.commit()
    return '<script>alert("삭제되었습니다.");location.href="/community/list"</script>'


@bp.route('/file_download/<string:file_name>')
@login_required
def file_download(file_name):
    try:
        path = os.getcwd()
        UPLOAD_FOLDER = os.path.join(path, 'pybo\\static\\upload_file\\')
        file_name = UPLOAD_FOLDER + file_name
        print(file_name)
        print("file_download success")
    except:
        print("file_download fail")
        return '<script>alert("error");</script>'
    return send_file(file_name, mimetype='image/png', as_attachment=True)


def file_upload(file):
    print("file_upload")
    filename = secure_filename(file.filename)
    extension = filename.split(".");
    allow_Extension = {"png", "jpg"}

    #허용된 확장자 리스트에 파일의 확장자가 존재할 경우 파일을 저장
    for i in allow_Extension:
      if(extension[1] == i):
            file.save(UPLOAD_FOLDER + "\\" + filename)
            return filename

    #파일이 저장이 안될경우 error 수신
    return "error"

    

pybo/views/vote_views.py
from flask import Blueprint, url_for, flash, g
from werkzeug.utils import redirect

from pybo import db
from pybo.models import Community, Notice, Answer, Anotice
from pybo.views.auth_views import login_required

bp = Blueprint('vote', __name__, url_prefix='/vote')


@bp.route('/community/<int:community_id>/')
@login_required
def community(community_id):
    _community = Community.query.get_or_404(community_id)
    if g.user == _community.user:
        # flash('본인이 작성한 글은 추천할 수 없습니다')
        # return '<script>alert("본인이 작성한 글은 추천할 수 없습니다.");</script>'
        return '<script>alert("본인이 작성한 글은 추천할 수 없습니다.");window.history.back();</script>'
    else:
        _community.voter.append(g.user)
        db.session.commit()
    return redirect(url_for('community.detail', community_id=community_id))


@bp.route('/answer/<int:answer_id>/')
@login_required
def answer(answer_id):
    _answer = Answer.query.get_or_404(answer_id)
    if g.user == _answer.user:
        return '<script>alert("본인이 작성한 글은 추천할 수 없습니다.");window.history.back();</script>'
    else:
        _answer.voter.append(g.user)
        db.session.commit()
    return redirect(url_for('community.detail', community_id=_answer.community.id))


# Notice

@bp.route('/notice/<int:notice_id>/')
@login_required
def notice(notice_id):
    _notice = Notice.query.get_or_404(notice_id)
    if g.user == _notice.user:
        return '<script>alert("본인이 작성한 글은 추천할 수 없습니다.");window.history.back();</script>'
    else:
        _notice.voter.append(g.user)
        db.session.commit()
    return redirect(url_for('notice.detail', notice_id=notice_id))


@bp.route('/anotice/<int:anotice_id>/')
@login_required
def anotice(anotice_id):
    _anotice = Anotice.query.get_or_404(anotice_id)
    if g.user == _anotice.user:
        return '<script>alert("본인이 작성한 글은 추천할 수 없습니다.");window.history.back();</script>'
    else:
        _anotice.voter.append(g.user)
        db.session.commit()
    return redirect(url_for('notice.detail', notice_id=_anotice.notice.id))

pybo/templates/community/community_detail.html
{% extends 'base.html' %}
{% block content %}
<title>{{ community.subject }}</title>
<div id="container my-3">
    <div id="contents" class="div-board create">
        <div class="container-warp list">
            {% for message in get_flashed_messages() %}
            <div class="alert alert-danger" role="alert">
                {{ message }}
            </div>
            {% endfor %}
            <h2 class="border-bottom py-2">{{ community.subject }}</h2>
            <div class="border-bottom user">
                <div class="left-border">
                    <div class="border-username">{{ community.user.username }}</div>
                    <div class="border-date">{{ community.create_date|datetime }}</div>
                    <div class="border-customers">조회 {{ community.hits }}</div>
                </div>
            </div>
            <div class="row my-3">
                <div class="col-11">
                    <!-- 기존내용 -->
                    <div class="card">
                        <div class="card-body">
                            <div class="card-text" style="white-space: pre-line;">
                                {{ community.content }}
                                {% if community.file != None %}
                                <img src="/community/file_download/{{ community.file }}">
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    {% if community.file != None %}
                    <div class="card-file">
                        <a href="/community/file_download/{{ community.file }}">
                            <div class="card-file-body">{{ community.file }}</div>
                        </a>
                    </div>
                    {% endif %}
                </div>
            </div>
            <div class="voter-box">
                <div class="bg-light text-center p-3 border font-weight-bolder mb-1">{{
                    community.voter|length }}
                </div>
                <a data-uri="{{ url_for('vote.community', community_id=community.id) }}"
                   class="recommend btn btn-sm btn-secondary btn-block my-1">추천</a>
            </div>
            {% if g.user == community.user %}
            <div class="my-32">
                <a href="{{ url_for('community.modify', community_id=community.id) }}"
                   class="btn btn-sm btn-outline-secondary">수정</a>
                <a href="#" class="delete btn btn-sm btn-outline-secondary"
                   data-uri="{{ url_for('community.delete', community_id=community.id) }}">삭제</a>
            </div>
            {% elif g.user.email == "biteup@biteup.com" %}
            <div class="my-32">
                <a href="#" class="delete btn btn-sm btn-outline-secondary"
                   data-uri="{{ url_for('community.delete', community_id=community.id) }}">삭제</a>
            </div>
            {% endif %}
            <h5 class="border-bottom my-3 py-2">댓글 : {{ community.answer_set|length }}개</h5>
            {% for answer in community.answer_set %}
            <div class="border-bottom background">
                <div class="row my-33">
                    <div class="col-11">  <!-- 답변영역 -->
                        <!-- 기존내용 -->
                        <div class="card my-3">
                            <div class="mb-2">
                                <div style="font-weight:bold">{{ answer.user.username }}</div>
                                <div style="margin-left:10px">
                                    <a id="goodButton" class="recommend btn btn-sm btn-secondary btn-block my-1"
                                       data-uri="{{ url_for('vote.answer', answer_id=answer.id) }}">
                            <span class="voter-number">
                                <img src="/static/good.png" style="height:17px;padding-bottom:5px;"/>
                                {{ answer.voter|length }}</span>
                                    </a>
                                </div>
                            </div>
                            <div class="card-body">
                                <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
                            </div>
                            <div style="display:block;">
                                <div style="display:inline;color:#afafaf">{{ answer.create_date|datetime }}
                                </div>
                                <div class="d-flex justify-content-end" style="display:inline;float:right;">
                                    {% if g.user == answer.user %}
                                    <div class="my-3">
                                        <a href="{{ url_for('answer.modify', answer_id=answer.id) }}"
                                           class="btn btn-sm btn-outline-secondary">수정</a>
                                        <a href="#" class="delete btn btn-sm btn-outline-secondary "
                                           data-uri="{{ url_for('answer.delete', answer_id=answer.id) }}">삭제</a>
                                    </div>
                                    {% elif g.user.email == "biteup@biteup.com" %}
                                    <div class="my-3">
                                        <a href="#" class="delete btn btn-sm btn-outline-secondary "
                                           data-uri="{{ url_for('answer.delete', answer_id=answer.id) }}">삭제</a>
                                    </div>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
            <form action="{{ url_for('answer.create', community_id=community.id) }}" method="post" class="my-3">
                {{ form.csrf_token }}
                <!-- 오류표시 Start -->
                {% for field, errors in form.errors.items() %}
                <div class="alert alert-danger" role="alert">
                    <strong>{{ form[field].label }}</strong>: {{ ', '.join(errors) }}
                </div>
                {% endfor %}
                <!-- 오류표시 End -->
                <div class="form-group">
            <textarea {% if not g.user %} disabled {% endif %}
                      name="content" id="content" class="form-control" rows="10"></textarea>
                </div>
                <input type="submit" value="답변등록" class="btn btn-primary">
            </form>
        </div>
        <div class="container-warp list board">
            <div class="detail_list">커뮤니티</div>
            <table class="table">
                <thead>
                <tr class="text-center thead-dark">
                    <th>No.</th>
                    <th style="width:50%">제목</th>
                    <th>작성자</th>
                    <th>작성일시</th>
                    <th>추천</th>
                    <th>조회</th>
                </tr>
                </thead>
                <tbody>
                {% if community_list %}
                {% for community in community_list.items %}
                <tr class="text-center">
                    <td>{{ community_list.total - ((community_list.page-1) * community_list.per_page) - loop.index0 }}
                    </td>
                    <td class="text-left">
                        <a href="{{ url_for('community.detail', community_id=community.id) }}">
                            {{ community.subject}}
                            {% if community.answer_set|length > 0 %}
                            <em>[{{ community.answer_set|length }}]</em>
                        </a>
                        {% endif %}
                    </td>
                    <td>{{ community.user.username }}</td>  <!-- 글쓴이 추가 -->
                    <td>{{ community.create_date|datetime }}</td>
                    <td>{{ community.voter|length }}</td>
                    <td>{{ community.hits }}</td>
                </tr>
                {% endfor %}
                {% else %}
                <tr>
                    <td colspan="3">내용이 없습니다.</td>
                </tr>
                {% endif %}
                </tbody>
            </table>
            <!-- 페이징처리 시작 -->
            <ul class="pagination justify-content-center">
                <!-- 이전페이지 -->
                {% if community_list.has_prev %}
                <li class="page-item">

                    <a class="page-link" data-page="{{ community_list.prev_num }}" href="#">이전</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
                </li>
                {% endif %}
                {% for page_num in community_list.iter_pages() %}
                {% if page_num %}
                {% if page_num != community_list.page %}
                <li class="page-item">
                    <a class="page-link" data-page="{{ page_num }}" href="#">{{ page_num }}</a>
                </li>
                {% else %}
                <li class="page-item active" aria-current="page">
                    <a class="page-link" href="#">{{ page_num }}</a>
                </li>
                {% endif %}
                {% else %}
                <li class="disabled">
                    <a class="page-link" href="#">...</a>
                </li>
                {% endif %}
                {% endfor %}
                <!-- 다음페이지 -->
                {% if community_list.has_next %}
                <li class="page-item">
                    <a class="page-link" data-page="{{ community_list.next_num }}" href="#">다음</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
                </li>
                {% endif %}
            </ul>
            <!-- 페이징처리 끝 -->
            <div class="col-4 input-group">
                <input type="text" class="form-control kw" value="{{ kw or '' }}" style="width:0;height:12px;">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
                </div>
            </div>
            <a href="{{ url_for('community.create') }}" class="btn btn-primary">글쓰기</a>
        </div>
        <form id="searchForm" method="get" action="{{ url_for('community._list') }}">
            <input type="hidden" id="kw" name="kw" value="{{ kw or '' }}">
            <input type="hidden" id="page" name="page" value="{{ page }}">
        </form>
    </div>
</div>
{% endblock %}
{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $(".delete").on('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = $(this).data('uri');
        }
    });
    $(".recommend").on('click', function() {
        if(confirm("정말로 추천하시겠습니까?")) {
            location.href = $(this).data('uri');
        }
    });
});

$(document).ready(function(){
    $(".page-link").on('click', function() {
        $("#page").val($(this).data("page"));
        $("#searchForm").submit();
    });
    $("#btn_search").on('click', function() {
        $("#kw").val($(".kw").val());
        $("#page").val(1);  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
        $("#searchForm").submit();
    });
});



</script>
{% endblock %}

pybo/templates/community/community_form.html
{% extends 'base.html' %}
{% block content %}
<title>커뮤니티 글쓰기</title>
<div id="container my-3">
    <div id="contents" class="div-board">
        <div class="container-warp list write">
            <h5 class="my-3 border-bottom pb-2">자유게시판</h5>
            <form method="post" class="post-form my-3" enctype = "multipart/form-data">
                {{ form.csrf_token }}
                <div class="form-group">
                    <label for="subject">제목</label>
                    <input type="text" class="form-control" name="subject" id="subject" required
                           value="{{ form.subject.data or '' }}">
                </div>
                <div class="form-group">
                    <label for="content">내용</label>
                    <textarea class="form-control" name="content"
                              id="content" rows="10" required>{{ form.content.data or '' }}</textarea>
                </div>
                <div class="form-group">
                    <label for="upload">파일</label>
                    <input type="file" class="form-control" name="file" id="upload">
                </div>
                <button type="submit" class="btn btn-primary">작성완료</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

pybo/templates/community/community_list.html
{% extends 'base.html' %}
{% block content %}
{% include "float.html" %}
<title>커뮤니티</title>
<div id="container my-3">
    <div id="contents" class="div-board">
        <div class="container-warp list">
            <div class="form_title">커뮤니티</div>
            <table class="table">
                <thead>
                <tr class="text-center thead-dark">
                    <th>No.</th>
                    <th style="width:50%">제목</th>
                    <th>작성자</th>
                    <th>작성일시</th>
                    <th>추천</th>
                    <th>조회</th>
                </tr>
                </thead>
                <tbody>
                {% if community_list %}
                {% for community in community_list.items %}
                <tr class="text-center">
                    <td>{{ community_list.total - ((community_list.page-1) * community_list.per_page) - loop.index0 }}</td>
                    <td class="text-left">
                        <a href="{{ url_for('community.detail', community_id=community.id) }}">
                            {{ community.subject}}
                            {% if community.answer_set|length > 0 %}
                            <em>[{{ community.answer_set|length }}]</em>
                        </a>
                        {% endif %}
                    </td>
                    <td>{{ community.user.username }}</td>  <!-- 글쓴이 추가 -->
                    <td>{{ community.create_date|datetime }}</td>
                    <td>{{ community.voter|length }}</td>
                    <td>{{ community.hits }}</td>
                </tr>
                {% endfor %}
                {% else %}
                <tr>
                    <td colspan="3">내용이 없습니다.</td>
                </tr>
                {% endif %}
                </tbody>
            </table>
            <!-- 페이징처리 시작 -->
            <ul class="pagination justify-content-center">
                <!-- 이전페이지 -->
                {% if community_list.has_prev %}
                <li class="page-item">

                    <a class="page-link" data-page="{{ community_list.prev_num }}" href="#">이전</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
                </li>
                {% endif %}
                {% for page_num in community_list.iter_pages() %}
                {% if page_num %}
                {% if page_num != community_list.page %}
                <li class="page-item">
                    <a class="page-link" data-page="{{ page_num }}" href="#">{{ page_num }}</a>
                </li>
                {% else %}
                <li class="page-item active" aria-current="page">
                    <a class="page-link" href="#">{{ page_num }}</a>
                </li>
                {% endif %}
                {% else %}
                <li class="disabled">
                    <a class="page-link" href="#">...</a>
                </li>
                {% endif %}
                {% endfor %}
                <!-- 다음페이지 -->
                {% if community_list.has_next %}
                <li class="page-item">
                    <a class="page-link" data-page="{{ community_list.next_num }}" href="#">다음</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
                </li>
                {% endif %}
            </ul>
            <!-- 페이징처리 끝 -->
            <div class="col-4 input-group">
                <input type="text" class="form-control kw" value="{{ kw or '' }}">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
                </div>
            </div>
            <a href="{{ url_for('community.create') }}" class="btn btn-primary">글쓰기</a>
        </div>
    </div>
</div>
<form id="searchForm" method="get" action="{{ url_for('community._list') }}">
    <input type="hidden" id="kw" name="kw" value="{{ kw or '' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
</form>
{% endblock %}
{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $(".page-link").on('click', function() {
        $("#page").val($(this).data("page"));
        $("#searchForm").submit();
    });
    $("#btn_search").on('click', function() {
        $("#kw").val($(".kw").val());
        $("#page").val(1);  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
        $("#searchForm").submit();
    });
});
</script>
{% endblock %}