pybo/views/auth_views.py
from datetime import datetime
from flask import Blueprint, url_for, render_template, flash, request, session, g
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import redirect

from pybo import db
from pybo.forms import UserCreateForm, UserLoginForm, PasswordResetForm, PasswordResetConfirmForm, AgreeForm, WithdrawalForm
from pybo.models import User
import functools

bp = Blueprint('auth', __name__, url_prefix='/')


@bp.route('/agree', methods=('POST', 'GET'))
def agree():
    if g.user:
        session.clear()
        return '<script>alert("로그아웃 됩니다.");location.href="/agree_re"</script>'
    else:
        return '<script>location.href="/agree_re"</script>'


@bp.route('/agree_re', methods=('GET', 'POST'))
def agree_re():
    form = AgreeForm()
    if request.method == 'POST' and form.validate_on_submit():
        if not user:
            user = User(agree=form.agree.data)
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('main.index'))
    return render_template('auth/agree_re.html', form=form)


@bp.route('/signup', methods=('POST', 'GET'))
def signup():
    if g.user:
        session.clear()
        return '<script>alert("로그아웃 됩니다.");location.href="/agree_re"</script>'
    else:
        return '<script>location.href="/signup_re"</script>'


@bp.route('/signup_re', methods=('GET', 'POST'))
def signup_re():
    form = UserCreateForm()
    if request.method == 'POST' and form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if not user:
            user = User(email=form.email.data,
                        password=generate_password_hash(form.password1.data),
                        username=form.username.data,
                        passwd_answer=form.passwd_answer.data,
                        create_date=datetime.now())
            db.session.add(user)
            db.session.commit()
            print("계정이 생성됨")
            print(form.email.data)
            return '<script>alert("계정이 생성되었습니다.");location.href="/"</script>'
        else:
            return '<script>alert("이미 존재하는 계정입니다.");location.href="/signup_re"</script>'
    return render_template('auth/signup.html', form=form)


@bp.route('/login', methods=('POST', 'GET'))
def login():
    if g.user:
        session.clear()
        return '<script>alert("로그아웃 됩니다.");location.href="/login_re"</script>'
    else:
        return '<script>location.href="/login_re"</script>'


@bp.route('/login_re', methods=('GET', 'POST'))
def login_re():
    form = UserLoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        error = None
        user = User.query.filter_by(email=form.email.data).first()
        if not user:
            error = '올바른 이메일 주소를 입력하세요'
        elif not check_password_hash(user.password, form.password.data):
            error = '비밀번호가 일치하지 않습니다'
        if error is None:
            print("로그인 : "+user.email)
            session.clear()
            session['user_id'] = user.id
            return redirect(url_for('index._list'))
        flash(error)
    return render_template('auth/login.html', form=form)


@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')
    if user_id is None:
        g.user = None
    else:
        g.user = User.query.get(user_id)


@bp.route('/logout')
def logout():
    print("로그아웃 : " + g.user.email)
    session.clear()
    return redirect(url_for('index._list'))


def login_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if g.user is None:
            return redirect(url_for('auth.login'))
        return view(**kwargs)

    return wrapped_view


@bp.route('/password_reset', methods=('GET', 'POST'))
def password_reset():
    form = PasswordResetForm()
    error = None
    if request.method == 'POST' and form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data,
                                    username=form.username.data,
                                    passwd_answer=form.passwd_answer.data).first()
        if not user:
            print("등록되지 않은 사용자 비밀번호 변경")
            return '<script>alert("등록되지 않은 사용자 정보입니다.");location.href="/password_reset"</script>'
        if error is None:
            user.password = generate_password_hash(form.password1.data)
            db.session.add(user)
            db.session.commit()
            print(user.email)
            print("비밀번호 변경됨")
            return '<script>alert("비밀번호가 변경되었습니다.");location.href="/login"</script>'

            # return redirect(url_for('auth.password_reset_confirm', id=form.email.data))
    return render_template('auth/password_reset.html', form=form)


# @bp.route('/password_reset_confirm', methods=('GET', 'POST'))
# def password_reset_confirm():
#     form = PasswordResetConfirmForm()
#     if request.method == 'POST' and form.validate_on_submit():
#         user = User.query.filter_by(email=request.args['id']).first()
#         user.password = generate_password_hash(form.password1.data)
#         db.session.add(user)
#         db.session.commit()
#         print(user.email)
#         print("비밀번호 변경됨")
#         return '<script>alert("비밀번호가 변경되었습니다.");location.href="/login"</script>'
#     return render_template('auth/password_reset_confirm.html', form=form)


@bp.route('/delete_user', methods=('GET', 'POST'))
@login_required
def delete_user():
    form = WithdrawalForm()
    if request.method == 'POST' and form.validate_on_submit():
        error = None
        if not check_password_hash(g.user.password, form.password.data):
            error = '<script>alert("비밀번호가 일치하지 않습니다.");location.href="/delete_user"</script>'
        if error is None:
            user = User.query.get(g.user.id)
            db.session.delete(user)
            db.session.commit()
            print("계정 탈퇴함")
            return '<script>alert("탈퇴되었습니다.");location.href="/"</script>'
    return render_template('auth/withdrawal.html', form=form)


@bp.route('/paper/provision')
def provision():
    return render_template('auth/provision.html')


@bp.route('/paper/privacy')
def privacy():
    return render_template('auth/privacy.html')

pybo/views/community_views.py
import os
from datetime import datetime, date, timedelta
from pybo.views.auth_views import login_required
from flask import Blueprint, render_template, request, url_for, g, flash, send_file
from werkzeug.utils import secure_filename

from .. import db
from ..forms import CommunityForm, AnswerForm
from ..models import Community, Answer, User

path = os.getcwd()
UPLOAD_FOLDER = os.path.join(path, 'pybo\\static\\upload_file')
bp = Blueprint('community', __name__, url_prefix='/community')

file_path = "templates/upload_file/"


@bp.route('/list')
@login_required
def _list():
    # 입력 파라미터
    page = request.args.get('page', type=int, default=1)
    kw = request.args.get('kw', type=str, default='')

    # 조회
    community_list = Community.query.order_by(Community.create_date.desc())
    if kw:
        search = '%%{}%%'.format(kw)
        sub_query = db.session.query(Answer.community_id, Answer.content, User.username) \
            .join(User, Answer.user_id == User.id).subquery()
        community_list = community_list \
            .join(User) \
            .outerjoin(sub_query, sub_query.c.community_id == Community.id) \
            .filter(Community.subject.ilike(search) |  # 제목
                    Community.content.ilike(search) |  # 내용
                    User.username.ilike(search) |  # 작성자
                    sub_query.c.content.ilike(search) |  # 답변내용
                    sub_query.c.username.ilike(search)  # 답변작성자
                    ) \
            .distinct()

    # 페이징
    community_list = community_list.paginate(page, per_page=10)
    return render_template('community/community_list.html', community_list=community_list, page=page, kw=kw)


@bp.route('/detail/<int:community_id>/')
@login_required
def detail(community_id):
    form = AnswerForm()
    community = Community.query.get_or_404(community_id)

    #조회수 증가
    community.hits = community.hits + 1
    db.session.commit()

    # 입력 파라미터
    page = request.args.get('page', type=int, default=1)
    kw = request.args.get('kw', type=str, default='')

    # 조회
    community_list = Community.query.order_by(Community.create_date.desc())
    if kw:
        search = '%%{}%%'.format(kw)
        sub_query = db.session.query(Answer.community_id, Answer.content, User.username) \
            .join(User, Answer.user_id == User.id).subquery()
        community_list = community_list \
            .join(User) \
            .outerjoin(sub_query, sub_query.c.community_id == Community.id) \
            .filter(Community.subject.ilike(search) |  # 제목
                    Community.content.ilike(search) |  # 내용
                    User.username.ilike(search) |  # 작성자
                    sub_query.c.content.ilike(search) |  # 답변내용
                    sub_query.c.username.ilike(search)  # 답변작성자
                    ) \
            .distinct()
    # 페이징
    community_list = community_list.paginate(page, per_page=10)
    return render_template('community/community_detail.html', community=community, form=form, community_list=community_list, page=page, kw=kw)


@bp.route('/create', methods=('GET', 'POST'))
@login_required
def create():
    form = CommunityForm()
    filename = None

    if request.method == 'POST' and form.validate_on_submit():
        if request.files['file']:
            filename = file_upload(request.files['file'])
            if(filename == "error"):
                return '<script>alert("허용된 확장자가 아닙니다.");location.href="/community/detail"</script>'

        community = Community(subject=form.subject.data, content=form.content.data, create_date=datetime.now(),
                              user=g.user, file=filename, hits=1)

        db.session.add(community)
        db.session.commit()

        #로그
        print("게시글 생성")
        print("작성자 : " + g.user.email)
        print("별명 : " + g.user.username)
        print("제목 : " + form.subject.data)
        print("내용 : "+ form.content.data)
        if filename is not None:
            print("업로드 파일 : "+ filename)
        ###
        return '<script>alert("작성 되었습니다.");location.href="/community/list"</script>'
    return render_template('community/community_form.html', form=form)


@bp.route('/modify/<int:community_id>', methods=('GET', 'POST'))
@login_required
def modify(community_id):
    community = Community.query.get_or_404(community_id)
    # 보안
    # if g.user != community.user:
    #     print("게시글 수정 권한 없음")
    #     print(g.user.email+"->"+community.user.email)
    #     return '<script>alert("수정권한이 없습니다.");location.href="/community/detail/' + str(community_id) + '"</script>'
    if request.method == 'POST':  # POST 요청
        form = CommunityForm()
        if form.validate_on_submit():
            if request.files['file']:
                filename = file_upload(request.files['file'])
                if(filename == "error"):
                    return '<script>alert("허용된 확장자가 아닙니다.");location.href="/community/detail"</script>'
                community.file = filename

            #로그
            print("게시글 수정됨")
            print(g.user.email+" -> "+community.user.email)
            print("제목 : "+community.subject+" -> "+form.subject.data)
            print("본문 : "+community.content+" -> "+form.content.data)
            ###

            community.subject = form.subject.data
            community.content = form.content.data
            community.modify_date = datetime.now()  # 수정일시 저장
            db.session.commit()

            return '<script>alert("수정되었습니다.");location.href="/community/detail/' + str(community_id) + '"</script>'
    else:  # GET 요청
        form = CommunityForm(obj=community)
    return render_template('community/community_form.html', form=form)


@bp.route('/delete/<int:community_id>')
@login_required
def delete(community_id):
    community = Community.query.get_or_404(community_id)
    if g.user != community.user and g.user.email != "biteup@biteup.com":
        print("게시글 삭제 권한 없음")
        print(g.user.email+" -> "+community.user.email)
        return '<script>alert("삭제 권한이 없습니다.");location.href="/community/detail/' + str(community_id) + '"</script>'

    print("게시글 삭제됨")
    print(g.user.email+" -> "+community.user.email)
    print("제목 : " + community.subject)
    print("본문 : " + community.content)
    ####

    db.session.delete(community)
    db.session.commit()
    return '<script>alert("삭제되었습니다.");location.href="/community/list"</script>'


@bp.route('/file_download/<string:file_name>')
@login_required
def file_download(file_name):
    try:
        path = os.getcwd()
        UPLOAD_FOLDER = os.path.join(path, 'pybo\\static\\upload_file\\')
        file_name = UPLOAD_FOLDER + file_name
        print(file_name)
        print("file_download success")
    except:
        print("file_download fail")
        return '<script>alert("error");</script>'
    return send_file(file_name, mimetype='image/png', as_attachment=True)


def file_upload(file):
    print("file_upload")
    filename = secure_filename(file.filename)
    extension = filename.split(".");
    allow_Extension = {"png", "jpg"}

    #허용된 확장자 리스트에 파일의 확장자가 존재할 경우 파일을 저장
    for i in allow_Extension:
      if(extension[1] == i):
            file.save(UPLOAD_FOLDER + "\\" + filename)
            return filename

    #파일이 저장이 안될경우 error 수신
    return "error"

    

pybo/templates/index/testpage.html
<h2>testpage</h2>
<span>
[고칠거]
    <br>
    <br>
[백엔드]
    <br>
1. 메인 trade 게시판 불러오기
    <br>
2. 탈퇴 기능
    <br>
3. 조회수 기능
    <br>
    <br>
    어드민아디 : biteup@biteup.com
    <br>
    비번 : admin
</span>
<div class="trade-middle-up">
    <div class="container-wrap main-list">
        <div class="fl">
            <h3>실시간 게시물</h3>
            <a href="{{ url_for('community._list') }}" class="more">
                <span>더보기</span>
            </a>
            <div class="list">
                <table class="table">
                    <thead>
                    <tr class="text-center thead-dark">
                    <th>No.</th>
                    <th style="width:50%">제목</th>
                    <th>작성자</th>
                </tr>
                    </thead>
                    <tbody>
                {% if community_list %}
                {% for community in community_list.items %}
                <tr class="text-center">
                    <td>{{ community_list.total - ((community_list.page-1) * community_list.per_page) - loop.index0 }}</td>
                    <td class="text-left">
                        <a href="{{ url_for('community.detail', community_id=community.id) }}">
                            {{ community.subject}}
                            {% if community.answer_set|length > 0 %}
                            <em>[{{ community.answer_set|length }}]</em>
                        </a>
                        {% endif %}
                    </td>
                    <td>{{ community.user.username }}</td>  <!-- 글쓴이 추가 -->
                </tr>
                {% endfor %}
                {% else %}
                <tr>
                    <td colspan="3">내용이 없습니다.</td>
                </tr>
                {% endif %}
                </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

pybo/templates/index/trade.html
{% extends 'base.html' %}
{% block content %}
{% include "float.html" %}
<title>biteup - 코인 커뮤니티</title>
<div class="container my-3">
    <div id="contents" class="div-trade">
        <div class="container-wrap main">
            <div class="trade-top left">
                <!-- TradingView Widget BEGIN -->
                <div class="tradingview-widget-container">
                    <div class="tradingview-widget-container__widget"></div>
                    <script type="text/javascript"
                            src="https://s3.tradingview.com/external-embedding/embed-widget-market-overview.js" async>
  {
  "title": "가상화폐",
  "title_raw": "Cryptocurrencies",
  "tabs": [
    {
      "title": "오버뷰",
      "title_raw": "Overview",
      "symbols": [
        {
          "s": "UPBIT:BTCKRW"
        },
        {
          "s": "BITSTAMP:BTCUSD"
        },
        {
          "s": "UPBIT:ETHKRW"
        },
        {
          "s": "UPBIT:SOLKRW"
        },
        {
          "s": "UPBIT:DOGEKRW"
        },
        {
          "s": "BITHUMB:UNIKRW"
        }

      ],
      "quick_link": {
        "title": "크립토커런시 더 보기",
        "href": "/markets/cryptocurrencies/prices-all/"
      }
    },
    {
      "title": "비트코인",
      "title_raw": "Bitcoin",
      "symbols": [
        {
          "s": "BITSTAMP:BTCUSD"
        },
        {
          "s": "COINBASE:BTCEUR"
        },
        {
          "s": "COINBASE:BTCGBP"
        },
        {
          "s": "BITFLYER:BTCJPY"
        },
        {
          "s": "CEXIO:BTCRUB"
        },
        {
          "s": "CME:BTC1!"
        }
      ],
      "quick_link": {
        "title": "비트코인 페어 더 보기",
        "href": "/symbols/BTCUSD/markets/"
      }
    },
    {
      "title": "이더리움",
      "title_raw": "Ethereum",
      "symbols": [
        {
          "s": "BITSTAMP:ETHUSD"
        },
        {
          "s": "KRAKEN:ETHEUR"
        },
        {
          "s": "COINBASE:ETHGBP"
        },
        {
          "s": "BITFLYER:ETHJPY"
        },
        {
          "s": "BINANCE:ETHBTC"
        },
        {
          "s": "BINANCE:ETHUSDT"
        }
      ],
      "quick_link": {
        "title": "이더리움 페어 더 보기",
        "href": "/symbols/ETHUSD/markets/"
      }
    },
    {
      "title": "솔라나",
      "title_raw": "Solana",
      "symbols": [
        {
          "s": "FTX:SOLUSD"
        },
        {
          "s": "BINANCE:SOLEUR"
        },
        {
          "s": "COINBASE:SOLGBP"
        },
        {
          "s": "BINANCE:SOLBTC"
        },
        {
          "s": "HUOBI:SOLETH"
        },
        {
          "s": "BINANCE:SOLUSDT"
        }
      ],
      "quick_link": {
        "title": "솔라나 페어 더 보기",
        "href": "/symbols/SOLUSD/markets/"
      }
    },
    {
      "title": "유니스왑",
      "title_raw": "Uniswap",
      "symbols": [
        {
          "s": "COINBASE:UNIUSD"
        },
        {
          "s": "KRAKEN:UNIEUR"
        },
        {
          "s": "COINBASE:UNIGBP"
        },
        {
          "s": "BINANCE:UNIBTC"
        },
        {
          "s": "KRAKEN:UNIETH"
        },
        {
          "s": "BINANCE:UNIUSDT"
        }
      ],
      "quick_link": {
        "title": "유니스왑 페어 더 보기",
        "href": "/symbols/UNIUSD/markets/"
      }
    }
  ],
  "title_link": "/markets/cryptocurrencies/prices-all/",
  "width": "100%",
  "height": 480,
  "showChart": true,
  "showFloatingTooltip": false,
  "locale": "kr",
  "isTransparent": true,
  "plotLineColorGrowing": "#2962FF",
  "plotLineColorFalling": "#2962FF",
  "belowLineFillColorGrowing": "rgba(41, 98, 255, 0.12)",
  "belowLineFillColorFalling": "rgba(41, 98, 255, 0.12)",
  "belowLineFillColorGrowingBottom": "rgba(41, 98, 255, 0)",
  "belowLineFillColorFallingBottom": "rgba(41, 98, 255, 0)",
  "gridLineColor": "rgba(240, 243, 250, 0)",
  "scaleFontColor": "rgba(120, 123, 134, 1)",
  "showSymbolLogo": true,
  "symbolActiveColor": "rgba(41, 98, 255, 0.12)",
  "colorTheme": "light"
}













                    </script>
                </div>
            </div>
            <div class="trade-top right">
                <!-- TradingView Widget BEGIN -->
                <div class="tradingview-widget-container">
                    <div class="tradingview-widget-container__widget"></div>
                    <script type="text/javascript"
                            src="https://s3.tradingview.com/external-embedding/embed-widget-events.js" async>
  {
  "colorTheme": "light",
  "isTransparent": true,
  "width": "100%",
  "height": 480,
  "locale": "kr",
  "importanceFilter": "-1,0,1",
  "currencyFilter": "KRW"
}













                    </script>
                </div>
                <!-- TradingView Widget END -->
            </div>
        </div>
    </div>
</div>
<div class="trade-datetime">
    <div style="text-align: center;">
            <span id="clock" style="color:#f0f0f0; font-size: 100px;font-family: 'Changa One', cursive;">clock</span>
        <script>
        var Target = document.getElementById("clock");
        function clock() {
            var time = new Date();
            var hours = time.getHours();
            var minutes = time.getMinutes();
            var seconds = time.getSeconds();

            Target.innerText =
            `${hours < 10 ? `0${hours}` : hours} : ${minutes < 10 ? `0${minutes}` : minutes} : ${seconds < 10 ? `0${seconds}` : seconds}`;
        }
        clock();
        setInterval(clock, 1000); // 1초마다 실행

        </script>
    </div>
    <div class="trade-middle-up">
        <div class="container-wrap main-list">
            <div class="fl">
                <div class="tb-cs">
                    <h4>실시간 게시물</h4>
                    <a href="{{ url_for('community._list') }}" class="more">
                    <span>더보기<img src="https://flybit.com/static/media/ic_coin_list_arrow.92126bde.svg"
                                  style="vertical-align:-4px;"></span>
                    </a>
                </div>
                <div class="list">
                    <table class="table trade">
                        <thead>
                        </thead>
                        <tbody>
                        {% if community_list %}
                        {% for community in community_list.items %}
                        <tr class="text-center">
                            <td class="num">{{ loop.index }}</td>
                            <td class="text-left">
                                <a href="{{ url_for('community.detail', community_id=community.id) }}">
                                    <span>{{ community.subject}}</span>
                                    {% if community.answer_set|length > 0 %}
                                    <em>[{{ community.answer_set|length }}]</em>
                                    {% endif %}
                                    <p>{{ community.user.username }}</p>
                                </a>
                            </td>
                            <td class="customers">
                                조회 {{ community.hits }}
                                <p>{{ community.create_date|datetime }}</p>
                            </td>
                        </tr>
                        {% endfor %}
                        {% else %}
                        <tr>
                            <td colspan="3">내용이 없습니다.</td>
                        </tr>
                        {% endif %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="trade-middle">
        <div class="trade-middle-center">
            <div>
                <h2>FOREX CROSS RATES</h2>
            </div>
            <!-- TradingView Widget BEGIN -->
            <div class="tradingview-widget-container">
                <div class="tradingview-widget-container__widget"></div>
                <script type="text/javascript"
                        src="https://s3.tradingview.com/external-embedding/embed-widget-forex-cross-rates.js" async>
  {
  "width": "100%",
  "height": "100%",
  "currencies": [
    "EUR",
    "USD",
    "JPY",
    "GBP",
    "CHF",
    "AUD",
    "CAD",
    "NZD",
    "CNY",
    "KRW"
  ],
  "isTransparent": false,
  "colorTheme": "light",
  "locale": "kr"
}







                </script>
            </div>
            <!-- TradingView Widget END -->
        </div>
    </div>
    <div class="trade-middle-down">
        <div class="textbox">
            <div>
                <div class="text-h1"> 바이트업에서 코인정보를 공유해봐요</div>
                <div class="text-h2"> 바이트업은
                    <span>가상자산 시황을 실시간으로 제공</span>합니다.
                </div>
                <div class="text-h3">
                    <a href="{{ url_for('auth.agree') }}" class="link-box btn">
                        회원가입
                    </a>
                    <a href="{{ url_for('auth.login') }}" class="link-text">
                        이미 회원이신가요?
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}