pybo/views/anotice_views.py
from datetime import datetime
from .auth_views import login_required
from flask import Blueprint, url_for, request, render_template, g, flash
from werkzeug.utils import redirect

from .. import db
from ..forms import AnoticeForm
from ..models import Anotice, Notice

bp = Blueprint('anotice', __name__, url_prefix='/anotice')


@bp.route('/create/<int:notice_id>', methods=('POST',))
@login_required
def create(notice_id):
    form = AnoticeForm()
    notice = Notice.query.get_or_404(notice_id)
    if form.validate_on_submit():
        content = request.form['content']
        anotice = Anotice(content=content, create_date=datetime.now(), user=g.user)
        notice.anotice_set.append(anotice)
        db.session.commit()
        return redirect(url_for('notice.detail', notice_id=notice_id))
    return render_template('notice/notice_detail.html', notice=notice, form=form)


@bp.route('/modify/<int:anotice_id>', methods=('GET', 'POST'))
@login_required
def modify(anotice_id):
    anotice = Anotice.query.get_or_404(anotice_id)
    form = AnoticeForm(obj=anotice)
    # 보안
    # if g.user != anotice.user:
    #     return '<script>alert("수정권한이 없습니다");location.href="/anotice/detail/' + str(anotice.notice.id) + '"</script>'
        
    if request.method == "POST":
        form = AnoticeForm()
        if form.validate_on_submit():
            form.populate_obj(anotice)
            anotice.modify_date = datetime.now()  # 수정일시 저장
            db.session.commit()
            return '<script>alert("수정되었습니다.");location.href="/notice/detail/' + str(anotice.notice.id) + '"</script>'
            # return redirect(url_for('notice.detail', notice_id=anotice.notice.id))

    return render_template('anotice/anotice_form.html', form=form)


@bp.route('/delete/<int:anotice_id>')
@login_required
def delete(anotice_id):
    anotice = Anotice.query.get_or_404(anotice_id)
    notice_id = anotice.notice.id
    #보안
    # if g.user != anotice.user:
    #     return '<script>alert("삭제권한이 없습니다");location.href="/notice/detail/'+str(notice_id)+'"</script>'
    # else:
    db.session.delete(anotice)
    db.session.commit()
    return '<script>alert("삭제되었습니다.");location.href="/notice/detail/'+str(notice_id) + '"</script>'
    # return redirect(url_for('notice.detail', notice_id=notice_id))

pybo/views/notice_views.py
import os
from datetime import datetime
from pybo.views.auth_views import login_required
from flask import Blueprint, render_template, request, url_for, g, flash, send_file
from werkzeug.utils import secure_filename

from .. import db
from ..forms import NoticeForm, AnoticeForm
from ..models import Notice, Anotice, User

path = os.getcwd()
UPLOAD_FOLDER = os.path.join(path, 'pybo\\static\\upload_file')
bp = Blueprint('notice', __name__, url_prefix='/notice')

file_path = "templates/upload_file/"


@bp.route('/list')
def _list():
    # 입력 파라미터
    page = request.args.get('page', type=int, default=1)
    kw = request.args.get('kw', type=str, default='')

    # 조회
    notice_list = Notice.query.order_by(Notice.create_date.desc())
    if kw:
        search = '%%{}%%'.format(kw)
        sub_query = db.session.query(Anotice.notice_id, Anotice.content, User.username) \
            .join(User, Anotice.user_id == User.id).subquery()
        notice_list = notice_list \
            .join(User) \
            .outerjoin(sub_query, sub_query.c.notice_id == Notice.id) \
            .filter(Notice.subject.ilike(search) |  # 제목
                    Notice.content.ilike(search) |  # 내용
                    User.username.ilike(search) |  # 작성자
                    sub_query.c.content.ilike(search) |  # 답변내용
                    sub_query.c.username.ilike(search)  # 답변작성자
                    ) \
            .distinct()

    # 페이징
    notice_list = notice_list.paginate(page, per_page=10)
    return render_template('notice/notice_list.html', notice_list=notice_list, page=page, kw=kw)


@bp.route('/detail/<int:notice_id>/')
def detail(notice_id):
    form = AnoticeForm()
    notice = Notice.query.get_or_404(notice_id)

    # 조회수 증가
    notice.hits = notice.hits + 1
    db.session.commit()

    # 입력 파라미터
    page = request.args.get('page', type=int, default=1)
    kw = request.args.get('kw', type=str, default='')

    # 조회
    notice_list = Notice.query.order_by(Notice.create_date.desc())
    if kw:
        search = '%%{}%%'.format(kw)
        sub_query = db.session.query(Anotice.notice_id, Anotice.content, User.username) \
            .join(User, Anotice.user_id == User.id).subquery()
        notice_list = notice_list \
            .join(User) \
            .outerjoin(sub_query, sub_query.c.notice_id == Notice.id) \
            .filter(Notice.subject.ilike(search) |  # 제목
                    Notice.content.ilike(search) |  # 내용
                    User.username.ilike(search) |  # 작성자
                    sub_query.c.content.ilike(search) |  # 답변내용
                    sub_query.c.username.ilike(search)  # 답변작성자
                    ) \
            .distinct()

    # 페이징
    notice_list = notice_list.paginate(page, per_page=10)
    return render_template('notice/notice_detail.html', notice=notice, form=form, notice_list=notice_list, page=page, kw=kw)


@bp.route('/create', methods=('GET', 'POST'))
@login_required
def create():
    if g.user.email == "biteup@biteup.com":
        print("create notice")
        form = NoticeForm()
        filename = None

        if request.method == 'POST' and form.validate_on_submit():
            if request.files['file']:
                filename = file_upload(request.files['file'])

            notice = Notice(subject=form.subject.data, content=form.content.data, create_date=datetime.now(),
                                user=g.user, file=filename, hits=1)

            db.session.add(notice)
            db.session.commit()
            return '<script>alert("작성 되었습니다.");location.href="/notice/list"</script>'
        return render_template('notice/notice_form.html', form=form)
    else:
        return '<script>alert("글쓰기 권한이 없습니다.");location.href="/"</script>'


@bp.route('/modify/<int:notice_id>', methods=('GET', 'POST'))
@login_required
def modify(notice_id):
    notice = Notice.query.get_or_404(notice_id)
    # 보안
    # if g.user != notice.user:
    #     return '<script>alert("수정 권한이 없습니다.");location.href="/notice/detail/' + str(notice_id) + '"</script>'
    if request.method == 'POST':  # POST 요청
        form = NoticeForm()
        if form.validate_on_submit():
            if request.files['file']:
                filename = file_upload(request.files['file'])
                notice.file = filename

            notice.content = form.content.data
            notice.subject = form.subject.data
            notice.modify_date = datetime.now()  # 수정일시 저장
            db.session.commit()
            # return redirect(url_for('notice.detail', notice_id=notice_id))
            return '<script>alert("수정되었습니다.");location.href="/notice/detail/' + str(notice_id) + '"</script>'
    else:  # GET 요청
        form = NoticeForm(obj=notice)
    return render_template('notice/notice_form.html', form=form)


@bp.route('/delete/<int:notice_id>')
@login_required
def delete(notice_id):
    notice = Notice.query.get_or_404(notice_id)
    # 보안
    # if g.user != notice.user and g.user.email != "biteup@biteup.com":
    #     return '<script>alert("삭제 권한이 없습니다.");location.href="/notice/detail/' + str(notice_id) + '"</script>'
    db.session.delete(notice)
    db.session.commit()
    # return redirect(url_for('notice._list'))
    return '<script>alert("삭제되었습니다.");location.href="/notice/list"</script>'


@bp.route('/file_download/<string:file_name>')
@login_required
def file_download(file_name):
    print("file_download success")
    try:
        path = os.getcwd()
        UPLOAD_FOLDER = os.path.join(path, 'pybo\\static\\upload_file\\')
        file_name = UPLOAD_FOLDER + file_name
        print(file_name)
    except:
        return '<script>alert("error");</script>'
    return send_file(file_name, mimetype='image/png', as_attachment=True)


def file_upload(file):
    print("file_upload")
    filename = secure_filename(file.filename)
    file.save(UPLOAD_FOLDER + "\\" + filename)
    return filename

pybo/views/vote_views.py
from flask import Blueprint, url_for, flash, g
from werkzeug.utils import redirect

from pybo import db
from pybo.models import Community, Notice, Answer, Anotice
from pybo.views.auth_views import login_required

bp = Blueprint('vote', __name__, url_prefix='/vote')


@bp.route('/community/<int:community_id>/')
@login_required
def community(community_id):
    _community = Community.query.get_or_404(community_id)
    if g.user == _community.user:
        # flash('본인이 작성한 글은 추천할 수 없습니다')
        # return '<script>alert("본인이 작성한 글은 추천할 수 없습니다.");</script>'
        return '<script>alert("본인이 작성한 글은 추천할 수 없습니다.");window.history.back();</script>'
    else:
        _community.voter.append(g.user)
        db.session.commit()
    return redirect(url_for('community.detail', community_id=community_id))


@bp.route('/answer/<int:answer_id>/')
@login_required
def answer(answer_id):
    _answer = Answer.query.get_or_404(answer_id)
    if g.user == _answer.user:
        return '<script>alert("본인이 작성한 글은 추천할 수 없습니다.");window.history.back();</script>'
    else:
        _answer.voter.append(g.user)
        db.session.commit()
    return redirect(url_for('community.detail', community_id=_answer.community.id))


# Notice

@bp.route('/notice/<int:notice_id>/')
@login_required
def notice(notice_id):
    _notice = Notice.query.get_or_404(notice_id)
    if g.user == _notice.user:
        return '<script>alert("본인이 작성한 글은 추천할 수 없습니다.");window.history.back();</script>'
    else:
        _notice.voter.append(g.user)
        db.session.commit()
    return redirect(url_for('notice.detail', notice_id=notice_id))


@bp.route('/anotice/<int:anotice_id>/')
@login_required
def anotice(anotice_id):
    _anotice = Anotice.query.get_or_404(anotice_id)
    if g.user == _anotice.user:
        return '<script>alert("본인이 작성한 글은 추천할 수 없습니다.");window.history.back();</script>'
    else:
        _anotice.voter.append(g.user)
        db.session.commit()
    return redirect(url_for('notice.detail', notice_id=_anotice.notice.id))

pybo/templates/notice/notice_detail.html
{% extends 'base.html' %}
{% block content %}
<title>{{ notice.subject }}</title>
<div id="container my-3">
    <div id="contents" class="div-board create">
        <div class="container-warp list">
            {% for message in get_flashed_messages() %}
            <div class="alert alert-danger" role="alert">
                {{ message }}
            </div>
            {% endfor %}
            <h2 class="border-bottom py-2">{{ notice.subject }}</h2>
            <div class="border-bottom user">
                <div class="left-border">
                    <div class="border-username">{{ notice.user.username }}</div>
                    <div class="border-date">{{ notice.create_date|datetime }}</div>
                    <div class="border-customers">
                        <span>조회 {{ notice.hits }}</span>
                    </div>
                </div>
            </div>
            <div class="row my-3">
                <div class="col-11">
                    <!-- 기존내용 -->
                    <div class="card">
                        <div class="card-body">
                            <div class="card-text" style="white-space: pre-line;">
                                {{ notice.content }}
                                {% if notice.file != None %}
                                <img src="/notice/file_download/{{ notice.file }}">
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    {% if notice.file != None %}
                    <div class="card-file">
                        <a href="/notice/file_download/{{ notice.file }}">
                            <div class="card-file-body">{{ notice.file }}</div>
                        </a>
                    </div>
                    {% endif %}
                </div>
            </div>
            <div class="voter-box">
                <div class="bg-light text-center p-3 border font-weight-bolder mb-1">{{
                    notice.voter|length }}
                </div>
                <a data-uri="{{ url_for('vote.notice', notice_id=notice.id) }}"
                   class="recommend btn btn-sm btn-secondary btn-block my-1">추천</a>
            </div>
            {% if g.user == notice.user %}
            <div class="my-32">
                <a href="{{ url_for('notice.modify', notice_id=notice.id) }}"
                   class="btn btn-sm btn-outline-secondary">수정</a>
                <a href="#" class="delete btn btn-sm btn-outline-secondary"
                   data-uri="{{ url_for('notice.delete', notice_id=notice.id) }}">삭제</a>
            </div>
            {% endif %}
            <h5 class="border-bottom my-3 py-2">댓글 : {{ notice.anotice_set|length }}</h5>
            {% for anotice in notice.anotice_set %}
            <div class="border-bottom background">
                <div class="row my-33">
                    <div class="col-11">  <!-- 답변영역 -->
                        <!-- 기존내용 -->
                        <div class="card my-3">
                            <div class="mb-2">
                                <div style="font-weight:bold">{{ anotice.user.username }}</div>
                                <div style="margin-left:10px">
                                    <a id="goodButton" class="recommend btn btn-sm btn-secondary btn-block my-1"
                                       data-uri="{{ url_for('vote.anotice', anotice_id=anotice.id) }}">
                            <span class="voter-number">
                                <img src="/static/good.png" style="height:17px;padding-bottom:5px;"/>
                                {{ anotice.voter|length }}</span>
                                    </a>
                                </div>
                            </div>
                            <div class="card-body">
                                <div class="card-text" style="white-space: pre-line;">{{ anotice.content }}</div>
                            </div>
                            <div style="display:block;">
                                <div style="display:inline;color:#a7a7a7">{{ anotice.create_date|datetime }}</div>
                                <div class="d-flex justify-content-end" style="display:inline;float:right;">
                                    {% if g.user == anotice.user %}
                                    <div class="my-3">
                                        <a href="{{ url_for('anotice.modify', anotice_id=anotice.id) }}"
                                           class="btn btn-sm btn-outline-secondary">수정</a>
                                        <a href="#" class="delete btn btn-sm btn-outline-secondary "
                                           data-uri="{{ url_for('anotice.delete', anotice_id=anotice.id) }}">삭제</a>
                                    </div>
                                    {% elif g.user.email == "biteup@biteup.com" %}
                                    <div class="my-3">
                                        <a href="#" class="delete btn btn-sm btn-outline-secondary "
                                           data-uri="{{ url_for('anotice.delete', anotice_id=anotice.id) }}">삭제</a>
                                    </div>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
            <form action="{{ url_for('anotice.create', notice_id=notice.id) }}" method="post" class="my-3">
                {{ form.csrf_token }}
                <!-- 오류표시 Start -->
                {% for field, errors in form.errors.items() %}
                <div class="alert alert-danger" role="alert">
                    <strong>{{ form[field].label }}</strong>: {{ ', '.join(errors) }}
                </div>
                {% endfor %}
                <!-- 오류표시 End -->
                <div class="form-group">
            <textarea {% if not g.user %} disabled {% endif %}
                      name="content" id="content" class="form-control" rows="10"></textarea>
                </div>
                <input type="submit" value="답변등록" class="btn btn-primary">
            </form>
        </div>
        <div class="container-warp list board">
            <div class="detail_list">공지사항</div>
            <table class="table">
                <thead>
                <tr class="text-center thead-dark">
                    <th>No.</th>
                    <th style="width:50%">제목</th>
                    <th>작성자</th>
                    <th>작성일시</th>
                    <th>추천</th>
                    <th>조회</th>
                </tr>
                </thead>
                <tbody>
                {% if notice_list %}
                {% for notice in notice_list.items %}
                <tr class="text-center">
                    <td>{{ notice_list.total - ((notice_list.page-1) * notice_list.per_page) - loop.index0 }}</td>
                    <td class="text-left">
                        <a href="{{ url_for('notice.detail', notice_id=notice.id) }}">
                            {{ notice.subject }}
                            {% if notice.anotice_set|length > 0 %}
                            <em>[{{ notice.anotice_set|length }}]</em>
                        </a>
                        {% endif %}
                    </td>
                    <td>{{ notice.user.username }}</td>  <!-- 글쓴이 추가 -->
                    <td>{{ notice.create_date|datetime }}</td>
                    <td>{{ notice.voter|length }}</td>
                    <td>{{ notice.hits }}</td>
                </tr>
                {% endfor %}
                {% else %}
                <tr>
                    <td colspan="3">내용이 없습니다.</td>
                </tr>
                {% endif %}
                </tbody>
            </table>
            <!-- 페이징처리 시작 -->
            <ul class="pagination justify-content-center">
                <!-- 이전페이지 -->
                {% if notice_list.has_prev %}
                <li class="page-item">

                    <a class="page-link" data-page="{{ notice_list.prev_num }}" href="#">이전</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
                </li>
                {% endif %}
                {% for page_num in notice_list.iter_pages() %}
                {% if page_num %}
                {% if page_num != notice_list.page %}
                <li class="page-item">
                    <a class="page-link" data-page="{{ page_num }}" href="#">{{ page_num }}</a>
                </li>
                {% else %}
                <li class="page-item active" aria-current="page">
                    <a class="page-link" href="#">{{ page_num }}</a>
                </li>
                {% endif %}
                {% else %}
                <li class="disabled">
                    <a class="page-link" href="#">...</a>
                </li>
                {% endif %}
                {% endfor %}
                <!-- 다음페이지 -->
                {% if notice_list.has_next %}
                <li class="page-item">
                    <a class="page-link" data-page="{{ notice_list.next_num }}" href="#">다음</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
                </li>
                {% endif %}
            </ul>
            <!-- 페이징처리 끝 -->
            <div class="col-4 input-group">
                <input type="text" class="form-control kw" value="{{ kw or '' }}" style="width:0;height:12px;">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
                </div>
            </div>
            {% if g.user.email == "biteup@biteup.com" %}
            <a href="{{ url_for('notice.create') }}" class="btn btn-primary">글쓰기</a>
            {% endif %}
        </div>
        <form id="searchForm" method="get" action="{{ url_for('notice._list') }}">
            <input type="hidden" id="kw" name="kw" value="{{ kw or '' }}">
            <input type="hidden" id="page" name="page" value="{{ page }}">
        </form>
    </div>
</div>
{% endblock %}
{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $(".delete").on('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = $(this).data('uri');
        }
    });
    $(".recommend").on('click', function() {
        if(confirm("정말로 추천하시겠습니까?")) {
            location.href = $(this).data('uri');
        }
    });
});

$(document).ready(function(){
    $(".page-link").on('click', function() {
        $("#page").val($(this).data("page"));
        $("#searchForm").submit();
    });
    $("#btn_search").on('click', function() {
        $("#kw").val($(".kw").val());
        $("#page").val(1);  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
        $("#searchForm").submit();
    });
});




</script>
{% endblock %}

pybo/templates/notice/notice_form.html
{% extends 'base.html' %}
{% block content %}
<title>공지사항</title>
<div id="container my-3">
    <div id="contents" class="div-board">
        <div class="container-warp list">
            <h5 class="my-3 border-bottom pb-2">공지사항</h5>
            <form method="post" class="post-form my-3" enctype = "multipart/form-data">
                {{ form.csrf_token }}
                <div class="form-group">
                    <label for="subject">제목</label>
                    <input type="text" class="form-control" name="subject" id="subject" required
                           value="{{ form.subject.data or '' }}">
                </div>
                <div class="form-group">
                    <label for="content">내용</label>
                    <textarea class="form-control" name="content"
                              id="content" rows="10" required>{{ form.content.data or '' }}</textarea>
                </div>
                <div class="form-group">
                    <label for="upload">파일</label>
                    <input type="file" class="form-control" name="file" id="upload">
                </div>
                <button type="submit" class="btn btn-primary">작성완료</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

pybo/templates/notice/notice_list.html
{% extends 'base.html' %}
{% block content %}
{% include "float.html" %}
<title>공지사항</title>
<div id="container my-3">
    <div id="contents" class="div-board">
        <div class="container-warp list">
            <div class="form_title">공지사항</div>
            <table class="table">
                <thead>
                <tr class="text-center thead-dark">
                    <th>No.</th>
                    <th style="width:50%">제목</th>
                    <th>작성자</th>
                    <th>작성일시</th>
                    <th>추천</th>
                    <th>조회</th>
                </tr>
                </thead>
                <tbody>
                {% if notice_list %}
                {% for notice in notice_list.items %}
                <tr class="text-center">
                    <td>{{ notice_list.total - ((notice_list.page-1) * notice_list.per_page) - loop.index0 }}</td>
                    <td class="text-left">
                        <a href="{{ url_for('notice.detail', notice_id=notice.id) }}">
                            {{ notice.subject }}
                            {% if notice.anotice_set|length > 0 %}
                            <em>[{{ notice.anotice_set|length }}]</em>
                        </a>
                        {% endif %}
                    </td>
                    <td>{{ notice.user.username }}</td>  <!-- 글쓴이 추가 -->
                    <td>{{ notice.create_date|datetime }}</td>
                    <td>{{ notice.voter|length }}</td>
                    <td>{{ notice.hits }}</td>
                </tr>
                {% endfor %}
                {% else %}
                <tr>
                    <td colspan="3">내용이 없습니다.</td>
                </tr>
                {% endif %}
                </tbody>
            </table>
            <!-- 페이징처리 시작 -->
            <ul class="pagination justify-content-center">
                <!-- 이전페이지 -->
                {% if notice_list.has_prev %}
                <li class="page-item">

                    <a class="page-link" data-page="{{ notice_list.prev_num }}" href="#">이전</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
                </li>
                {% endif %}
                {% for page_num in notice_list.iter_pages() %}
                {% if page_num %}
                {% if page_num != notice_list.page %}
                <li class="page-item">
                    <a class="page-link" data-page="{{ page_num }}" href="#">{{ page_num }}</a>
                </li>
                {% else %}
                <li class="page-item active" aria-current="page">
                    <a class="page-link" href="#">{{ page_num }}</a>
                </li>
                {% endif %}
                {% else %}
                <li class="disabled">
                    <a class="page-link" href="#">...</a>
                </li>
                {% endif %}
                {% endfor %}
                <!-- 다음페이지 -->
                {% if notice_list.has_next %}
                <li class="page-item">
                    <a class="page-link" data-page="{{ notice_list.next_num }}" href="#">다음</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
                </li>
                {% endif %}
            </ul>
            <!-- 페이징처리 끝 -->
            <div class="col-4 input-group">
                <input type="text" class="form-control kw" value="{{ kw or '' }}">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
                </div>
            </div>
            {% if g.user.email == "biteup@biteup.com" %}
            <a href="{{ url_for('notice.create') }}" class="btn btn-primary">글쓰기</a>
            {% endif %}
        </div>
    </div>
</div>
<form id="searchForm" method="get" action="{{ url_for('notice._list') }}">
    <input type="hidden" id="kw" name="kw" value="{{ kw or '' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
</form>
{% endblock %}
{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $(".page-link").on('click', function() {
        $("#page").val($(this).data("page"));
        $("#searchForm").submit();
    });
    $("#btn_search").on('click', function() {
        $("#kw").val($(".kw").val());
        $("#page").val(1);  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
        $("#searchForm").submit();
    });
});


</script>
{% endblock %}