pybo/views/auth_views.py
from datetime import datetime
from flask import Blueprint, url_for, render_template, flash, request, session, g
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import redirect

from pybo import db
from pybo.forms import UserCreateForm, UserLoginForm, PasswordResetForm, PasswordResetConfirmForm, AgreeForm, WithdrawalForm
from pybo.models import User
import functools

bp = Blueprint('auth', __name__, url_prefix='/')


@bp.route('/agree', methods=('POST', 'GET'))
def agree():
    if g.user:
        session.clear()
        return '<script>alert("로그아웃 됩니다.");location.href="/agree_re"</script>'
    else:
        return '<script>location.href="/agree_re"</script>'


@bp.route('/agree_re', methods=('GET', 'POST'))
def agree_re():
    form = AgreeForm()
    if request.method == 'POST' and form.validate_on_submit():
        if not user:
            user = User(agree=form.agree.data)
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('main.index'))
    return render_template('auth/agree_re.html', form=form)


@bp.route('/signup', methods=('POST', 'GET'))
def signup():
    if g.user:
        session.clear()
        return '<script>alert("로그아웃 됩니다.");location.href="/agree_re"</script>'
    else:
        return '<script>location.href="/signup_re"</script>'


@bp.route('/signup_re', methods=('GET', 'POST'))
def signup_re():
    form = UserCreateForm()
    if request.method == 'POST' and form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if not user:
            user = User(email=form.email.data,
                        password=generate_password_hash(form.password1.data),
                        username=form.username.data,
                        passwd_answer=form.passwd_answer.data,
                        create_date=datetime.now())
            db.session.add(user)
            db.session.commit()
            print("계정이 생성됨")
            print(form.email.data)
            return '<script>alert("계정이 생성되었습니다.");location.href="/"</script>'
        else:
            return '<script>alert("이미 존재하는 계정입니다.");location.href="/signup_re"</script>'
    return render_template('auth/signup.html', form=form)


@bp.route('/login', methods=('POST', 'GET'))
def login():
    if g.user:
        session.clear()
        return '<script>alert("로그아웃 됩니다.");location.href="/login_re"</script>'
    else:
        return '<script>location.href="/login_re"</script>'


@bp.route('/login_re', methods=('GET', 'POST'))
def login_re():
    form = UserLoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        error = None
        user = User.query.filter_by(email=form.email.data).first()
        if not user:
            error = '올바른 이메일 주소를 입력하세요'
        elif not check_password_hash(user.password, form.password.data):
            error = '비밀번호가 일치하지 않습니다'
        if error is None:
            print("로그인 : "+user.email)
            session.clear()
            session['user_id'] = user.id
            return redirect(url_for('index._list'))
        flash(error)
    return render_template('auth/login.html', form=form)


@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')
    if user_id is None:
        g.user = None
    else:
        g.user = User.query.get(user_id)


@bp.route('/logout')
def logout():
    print("로그아웃 : " + g.user.email)
    session.clear()
    return redirect(url_for('index._list'))


def login_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if g.user is None:
            return redirect(url_for('auth.login'))
        return view(**kwargs)

    return wrapped_view


@bp.route('/password_reset', methods=('GET', 'POST'))
def password_reset():
    form = PasswordResetForm()
    error = None
    if request.method == 'POST' and form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data,
                                    username=form.username.data,
                                    passwd_answer=form.passwd_answer.data).first()
        if not user:
            print("등록되지 않은 사용자 비밀번호 변경")
            return '<script>alert("등록되지 않은 사용자 정보입니다.");location.href="/password_reset"</script>'
        if error is None:
            user.password = generate_password_hash(form.password1.data)
            db.session.add(user)
            db.session.commit()
            print(user.email)
            print("비밀번호 변경됨")
            return '<script>alert("비밀번호가 변경되었습니다.");location.href="/login"</script>'

            # return redirect(url_for('auth.password_reset_confirm', id=form.email.data))
    return render_template('auth/password_reset.html', form=form)


# @bp.route('/password_reset_confirm', methods=('GET', 'POST'))
# def password_reset_confirm():
#     form = PasswordResetConfirmForm()
#     if request.method == 'POST' and form.validate_on_submit():
#         user = User.query.filter_by(email=request.args['id']).first()
#         user.password = generate_password_hash(form.password1.data)
#         db.session.add(user)
#         db.session.commit()
#         print(user.email)
#         print("비밀번호 변경됨")
#         return '<script>alert("비밀번호가 변경되었습니다.");location.href="/login"</script>'
#     return render_template('auth/password_reset_confirm.html', form=form)


@bp.route('/delete_user', methods=('GET', 'POST'))
@login_required
def delete_user():
    form = WithdrawalForm()
    if request.method == 'POST' and form.validate_on_submit():
        error = None
        if not check_password_hash(g.user.password, form.password.data):
            error = '<script>alert("비밀번호가 일치하지 않습니다.");location.href="/delete_user"</script>'
        if error is None:
            user = User.query.get(g.user.id)
            db.session.delete(user)
            db.session.commit()
            print("계정 탈퇴함")
            return '<script>alert("탈퇴되었습니다.");location.href="/"</script>'
    return render_template('auth/withdrawal.html', form=form)


@bp.route('/paper/provision')
def provision():
    return render_template('auth/provision.html')


@bp.route('/paper/privacy')
def privacy():
    return render_template('auth/privacy.html')

pybo/views/contact_views.py
from flask import Blueprint, url_for, render_template, request
from werkzeug.utils import redirect
from datetime import datetime

from .. import db
from ..forms import ContactForm
from ..models import Contact

bp = Blueprint('contact', __name__, url_prefix='/contact')


@bp.route('/qna', methods=('GET', 'POST'))
def qna():
    form = ContactForm()
    if request.method == 'POST' and form.validate_on_submit():
        contact = Contact(email=form.email.data, username=form.username.data, subject=form.subject.data, message=form.message.data,
                          create_date=datetime.today())
        db.session.add(contact)
        db.session.commit()
        return '<script>alert("작성되었습니다.");location.href="/"</script>'
    return render_template('contact/contact_form.html', form=form)

pybo/views/index_views.py
from flask import Blueprint, render_template, request, url_for, g, flash, send_file
from werkzeug.utils import secure_filename
from pybo.views.auth_views import login_required

from .. import db
from ..forms import CommunityForm, AnswerForm
from ..models import Community, Answer, User

bp = Blueprint('index', __name__, url_prefix='/')


@bp.route('/')
def _list():
    # 입력 파라미터
    page = request.args.get('page', type=int, default=1)
    kw = request.args.get('kw', type=str, default='')

    # 조회
    community_list = Community.query.order_by(Community.create_date.desc())
    if kw:
        search = '%%{}%%'.format(kw)
        sub_query = db.session.query(Answer.community_id, Answer.content, User.username) \
            .join(User, Answer.user_id == User.id).subquery()
        community_list = community_list \
            .join(User) \
            .outerjoin(sub_query, sub_query.c.community_id == Community.id) \
            .filter(Community.subject.ilike(search) |  # 제목
                    Community.content.ilike(search) |  # 내용
                    User.username.ilike(search) |  # 작성자
                    sub_query.c.content.ilike(search) |  # 답변내용
                    sub_query.c.username.ilike(search)  # 답변작성자
                    ) \
            .distinct()

    # 페이징
    community_list = community_list.paginate(page, per_page=5)
    return render_template('index/trade.html', community_list=community_list, page=page, kw=kw)


@bp.route('/exchange')
@login_required
def exchange():
    return render_template('index/exchange.html')


@bp.route('/testpage')
def testpage():
    return render_template('index/testpage.html')

pybo/views/profile_views.py
from flask import Blueprint, url_for, render_template, flash, g, request
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import redirect
from pybo.views.auth_views import login_required

from pybo import db
from pybo.forms import EditProfileForm, EditPasswordForm
from pybo.models import User

bp = Blueprint('profile', __name__, url_prefix='/profile')


@bp.route('/', methods=('GET', 'POST'))
@login_required
def edit():
    form = EditProfileForm()
    if request.method == 'POST' and form.validate_on_submit():
        try:
            email = g.user.email
            user = User.query.filter_by(email=email).first()
            user.username = request.form['username']
            user.location = request.form['location']
            user.about_me = request.form['about_me']
            db.session.add(user)
            db.session.commit()
            return '<script>alert("프로필을 수정하였습니다.");location.href=/profile/</script>'
        except:
            print("profile edit error")
            return '<script>alert("이미 존재하는 이름입니다.");location.href=/profile/</script>'
    return render_template('profile/profile_edit.html', form=form)


@bp.route('/reset', methods=('GET', 'POST'))
def reset():
    form = EditPasswordForm()
    if request.method == 'POST' and form.validate_on_submit():
        user = User.query.filter_by(email=g.user.email).first()
        if not check_password_hash(user.password, form.password.data):
            print("비밀번호 변경 실패")
            return '<script>alert("현재 비밀번호가 일치하지 않습니다.");location.href="/profile/reset"</script>'
        else :
            if form.password1.data == form.password2.data:
                user.password = generate_password_hash(form.password1.data)
                db.session.add(user)
                db.session.commit()
                print("비밀번호 변경 성공")
                print(g.user.email + " -> " + user.email)
                return '<script>alert("비밀번호가 변경되었습니다");location.href=/profile/</script>'
    return render_template('profile/profile_reset.html', form=form)

pybo/templates/base.html
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}">
    <!-- pybo CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">

    <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='/icon.png') }}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Changa+One&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap" rel="stylesheet">
    <!-- jQuery JS -->
    <script src="{{ url_for('static', filename='jquery-3.6.0.min.js') }}"></script>
    <!-- Bootstrap JS -->
    <script src="{{ url_for('static', filename='bootstrap.min.js') }}"></script>
    <script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
</head>
<body style="overflow-x: hidden">
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- 자바스크립트 Start -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End -->
{% include "footer.html" %}
<!--하단info-->

<!-- 상단으로 이동하기 버튼 -->
<script>
$(window).scroll(function(){
	if ($(this).scrollTop() > 300){
		$('.btn_gotop').show();
	} else{
		$('.btn_gotop').hide();
	}
});
$('.btn_gotop').click(function(){
	$('html, body').animate({scrollTop:0});
	return false;
});

</script>
<div style="position:fixed; bottom:35px; right:30px; z-index:99;">
    <a href="#" class="btn_gotop">
        <img src="/static/topbutton.png" style="width:50px;">
    </a>
</div>
</body>
</html>

pybo/templates/float.html
<!-- TradingView Widget BEGIN -->
    <div class="tradingview-widget-container float">
        <div class="tradingview-widget-container__widget"></div>
        <script type="text/javascript" src="https://s3.tradingview.com/external-embedding/embed-widget-ticker-tape.js"
                async>
  {
  "symbols": [
    {
      "proName": "FOREXCOM:SPXUSD",
      "title": "S&P 500"
    },
    {
      "proName": "FOREXCOM:NSXUSD",
      "title": "US 100"
    },
    {
      "proName": "FX_IDC:EURUSD",
      "title": "EUR/USD"
    },
    {
      "description": "비트코인KRW",
      "proName": "UPBIT:BTCKRW"
    },
    {
      "proName": "BITSTAMP:BTCUSD",
      "title": "비트코인"
    },
    {
      "proName": "BITSTAMP:ETHUSD",
      "title": "이더리움"
    },
    {
      "description": "BTCUSDT",
      "proName": "BINANCE:BTCUSDT"
    },
    {
      "description": "BTCUSDTPERP",
      "proName": "BINANCE:BTCUSDTPERP"
    },
    {
      "description": "BTCUSDT",
      "proName": "BYBIT:BTCUSDT"
    },
    {
      "description": "도지코인",
      "proName": "BINANCE:DOGEUSDT"
    },
    {
      "description": "TRXUSDT",
      "proName": "BINANCE:TRXUSDT"
    },
    {
      "description": "SOLUSDT",
      "proName": "BINANCE:SOLUSDT"
    }
  ],
  "showSymbolLogo": true,
  "colorTheme": "light",
  "isTransparent": false,
  "displayMode": "regular",
  "locale": "kr"
}
        </script>
    </div>
    <!-- TradingView Widget END -->

pybo/templates/footer.html
<div class="trade-low">
    <div class="container-wrap foot">
        <table>
            <tbody>
            <tr>
                <td>
                    <a href="https://www.upbit.com/" target="_blank">
                        <img style="height:15px;" src="https://w.namu.la/s/d6a168557627305b679e99fec1029ff22e8a0cb093ebae3de77e0b2657da8cd3269303c39641bbab78cbe34d938a1519283d3c5fb63a9cf090b97d71dbde36f6ad630dee81b556f5374b73388066e668f4ccce911790584a4df907bee061e448" alt="업바이트">
                    </a>
                </td>
                <td>
                    <a href="https://www.bithumb.com/" target="_blank">
                        <img style="height:20px;" src="https://w.namu.la/s/7e4d12e876e5f13ebcd9e844518418489ab97f0d46794df894fa3796bdb72abefaa34b0cc38de74d2bb1d6bb3d301644e15299a5f154de361f253f22ef62f4a932a43774a105f2cb8097dfc88b839db7eead1a0167fc1d802da401b182cd2df5" alt="빗썸">
                    </a>
                </td>
                <td>
                    <a href="https://coinone.co.kr/" target="_blank">
                        <img style="height:15px;" src="https://w.namu.la/s/fa00b78cdbb9011afb073ac76b7f22a39b432014be4e23cee2f24bbea0dc3a6c35bb74fe4debedfc0e49846216cb071bfe731457328b55b7d25cdcc0d83f822309e45e09abfc7e535ebbe8f1724d3d577909f6fe4fcf86271afff1482c323616" alt="코인원">
                    </a>
                </td>
                <td>
                    <a href="https://www.korbit.co.kr/" target="_blank">
                        <img style="height:15px;" src="https://w.namu.la/s/720d205457278c364768873f979eff47a6797f25b7dde47d591ee3156d055d38fb21c67b0230e417d9863173a7612051d4b41f1d4fca4ee0bbc4442b5822295c1fdce9779630bc7f90bb2488e16317289fb796bd6b94d19fc3b35f7922cd7a09" alt="코빗">
                    </a>
                </td>
                <td>
                    <a href="https://www.gopax.co.kr/" target="_blank">
                        <img style="height:15px;" src="https://w.namu.la/s/e881bcd5be5880484efa0582f43173a4103abbc0b8e533d621c4384fbf3f6201e26ecfb873717f20fe4f67ba50f1a3ca0d60b0e31894e5974b8c7e11684cb083fff4a1ac2332da16754c1c7d4e85df5b772f4c108ea0d1bc63d4017a9d4f2865" alt="고팍스">
                    </a>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</div>
<!--footer-->
<footer id="footer-wrap">
    <div id="footer" class="div-foot">
        <div class="l-logo">
            <h2>
                <span class="blind">biteup</span>
            </h2>
        </div>
        <div class="l-info">
            <div class="l-link">
                <ul class="l-item">
                    <li class="item">
                        <a class="it" href="/paper/provision">이용약관</a>
                    </li>
                    <li class="item">
                        <a class="it" href="/paper/privacy">개인정보취급방침</a>
                    </li>
                    <li class="item">
                        <a class="it" href="{{ url_for('contact.qna') }}">문의하기</a>
                    </li>
                    <li class="item">
                        <a class="it" href="{{ url_for('notice._list') }}">공지사항</a>
                    </li>
                </ul>
                <ul class="l-txt">
                    <li>
                        <span>주식회사 바이트업</span>
                    </li>
                    <li>
                        <span>대표자: Web8</span>
                    </li>
                    <li>
                        <span>메일: biteup@biteup.com</span>
                    </li>
                </ul>
            </div>
        </div>
        <div class="copyright">
            <span>Copyright © biteup. All rights reserved.</span>
        </div>
    </div>
</footer>

pybo/templates/form_errors.html
<!-- 필드오류 -->
{% for field, errors in form.errors.items() %}
<div class="alert alert-danger" role="alert">
    <strong>{{ form[field].label }}</strong>: {{ ', '.join(errors) }}
</div>
{% endfor %}
<!-- flash 오류 -->
{% for message in get_flashed_messages() %}
<div class="alert alert-danger" role="alert">
    {{ message }}
</div>
{% endfor %}

pybo/templates/navbar.html
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <h1 id="logo">
        <a href="{{ url_for('index._list') }}">
            <span class="blind">biteup</span>
        </a>
        </h1>
        <ul class="navbar-nav">
            <li class="nav-item ">
                <a class="nav-link" onclick="alert('현재 준비중입니다'); return false;" href="">
                    <span>코인소식</span>
                </a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{{ url_for('community._list') }}">
                    <span>커뮤니티</span>
                </a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{{ url_for('index.exchange') }}">
                    <span>분석/차트</span>
                </a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{{ url_for('notice._list') }}">
                    <span>공지사항</span>
                </a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{{ url_for('contact.qna') }}">
                    <span>Contact Us</span>
                </a>
            </li>
        </ul>
        <div class="member-desktop">
        {% if g.user %}
        <div class="navbar-out">
            <div class="nav-box ">
                <a class="nav-name" href="{{ url_for('profile.edit') }}">{{ g.user.username }}<span style="font-size:12px;">님 방가!</span></a>
            </div>
            <div class="nav-box ">
                <a class="nav-logout" href="{{ url_for('auth.logout') }}">LOGOUT</a>
            </div>
        </div>
        {% else %}
        <div class="navbar-lo">
            <div class="nav-box ">
                <a class="nav-re" href="{{ url_for('auth.agree') }}">SIGN UP</a>
            </div>
            <div class="nav-box ">
                <a class="nav-login" href="{{ url_for('auth.login') }}">LOGIN</a>
            </div>
        </div>
        {% endif %}
            </div>
    </div>
</nav>